apiVersion: run.tanzu.vmware.com/v1alpha1       #Tanzu Kubernetes Grid (TKG) API endpoint
kind: TanzuKubernetesCluster                    #Tanzu Kubernetes Cluster (TKC) kind
metadata:
  name: tkcSingeNodeCluster                     #cluster name
spec:
  distribution:
    version: v1.18                              #Tanzu Kubernetes Release (TKR) version
  topology:
    controlPlane:
      count: 1                                  #number of control plane nodes
      class: guaranteed-small                   #vmclass for control plane nodes
      storageClass: standard                    #storageclass for control plane
    workers:
      count: 1                                  #number of worker nodes
      class: guaranteed-small                   #vmclass for worker nodes
      storageClass: standard                    #storageclass for worker nodes
