apiVersion: v1
kind: Pod
metadata:
  name: kuard
  namespace: samples
spec:
  containers:
  - image: harbor.labu.ditec.dtra.mil/samples/kuard-amd64:blue
    name: kuard
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
