---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cert-manager-sa
  namespace: vmtools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-cert-manager-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-cert-manager-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-cert-manager-cluster-role
subjects:
- kind: ServiceAccount
  name: cert-manager-cert-manager-sa
  namespace: vmtools
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: vmtools
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.1.0+vmware.1-tkg.2
      prereleases: {}
  serviceAccountName: cert-manager-cert-manager-sa
