---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour-contour-sa
  namespace: vmtools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contour-contour-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contour-contour-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour-contour-cluster-role
subjects:
- kind: ServiceAccount
  name: contour-contour-sa
  namespace: vmtools
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: vmtools
spec:
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: 1.17.1+vmware.1-tkg.1
      prereleases: {}
  serviceAccountName: contour-contour-sa
  values:
  - secretRef:
      name: contour-contour-values
