#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-harbor-sa    
  namespace: kapp-gitops-mgmt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harbor-harbor-cluster-role    
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harbor-harbor-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harbor-harbor-cluster-role
subjects:
- kind: ServiceAccount
  name: harbor-harbor-sa
  namespace: kapp-gitops-mgmt
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-harbor-sa
  namespace: kapp-gitops-mgmt
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall 
metadata:
  name: harbor
  namespace: kapp-gitops-mgmt
spec:                      
  packageRef:
    refName: harbor.tanzu.vmware.com
    versionSelection:
      constraints: 2.2.3+vmware.1-tkg.1
      prereleases: {}  
  serviceAccountName: harbor-harbor-sa
  values:  
  - secretRef:
      name: harbor-harbor-values
