apiVersion: v1
kind: Secret
metadata:
  name:  harbor-harbor-values
  namespace: vmtools
type: Opaque
stringData:
  harbor-values.yaml: |
    namespace: harbor
    hostname: harbor.lab03.virtual.automatestuff.io
    port:
      https: 443
    logLevel: info
    tlsCertificate:
      tls.crt: |
        -----BEGIN CERTIFICATE-----
        MIIF/TCCA+WgAwIBAgIUZtEKhHk1xsaKPtCPJfLkiy0dX18wDQYJKoZIhvcNAQEN
        BQAwazELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlROMREwDwYDVQQHDAhSb2Nrd29v
        ZDEMMAoGA1UECgwDTGFiMQswCQYDVQQLDAIwMzEhMB8GA1UEAwwYdmlydHVhbC5h
        dXRvbWF0ZXN0dWZmLmlvMB4XDTIyMDMwNDIxMzM0MVoXDTMyMDMwMTIxMzM0MVow
        eDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlROMREwDwYDVQQHDAhSb2Nrd29vZDEM
        MAoGA1UECgwDTGFiMQswCQYDVQQLDAIwMzEuMCwGA1UEAwwlaGFyYm9yLmxhYjAz
        LnZpcnR1YWwuYXV0b21hdGVzdHVmZi5pbzCCAiIwDQYJKoZIhvcNAQEBBQADggIP
        ADCCAgoCggIBAKgJCq3eDVTTtgHFYHdtdmb6BoLB4lwNo4MeAnTFUtJibE9QOkAp
        WAX9tCx1pRyEiPGmphevgieiU5ovh2vCBwgR9q4EuBXHl16HmOlaMBBidTav7BQO
        NhK3RQARh0M1rX2yzjmHEN/GQYJov26yx6yS+KFoGwaeEP0bKR92U5iO5s/H6d+D
        61EY2PJaOzHXlwEqB1OlqhmduXDtj5NYC72xSoPXWkDb41XIo1kQP8O8iUixGIKY
        hrX/6XxpWbOkf4vBBhHGWPNsTnVf/9KuHIM6veUIF2xu45pm2kdIXylyl7U+vust
        BQQmyJlbDjfHgVrLue55UqM+uM59ZpW0nowWvwBDeliYRH99bE5F+nV/hs85qfgY
        c/c/0tr1oskQLUAAF/jyNOQsFThtcpLAqPsDGIpXRMN0o7uPQt/IpfxwGZ5IImtW
        pzbHUTFb6SJXB1GP2Ir5TjqHs+FSXLaWg8LYE5x1UHRTT4w0iYpk0cZo8Cvt2cP5
        WUHQMwv9cKBPR4jSyTGy3/b1s42RgscAyBE/NtBsStcnuTciAWBhwtz9+VOwRijc
        SV1cUSjfcc/WgXGUN5sLt5UoVDs/zr5Q+6yxJuuT4aBSRHMFCFeAgvMA8n/o7Ex/
        hN4BVpYdDeahEtnBvQ6lWwSJgIjSSWQ+UjA08P7DoQ6tP5kelQiS7G1zAgMBAAGj
        gYswgYgwHwYDVR0jBBgwFoAUlbFTEi04ocYIH+Z92sU5upglOSwwCQYDVR0TBAIw
        ADALBgNVHQ8EBAMCBPAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwOAYDVR0RBDEwL4Il
        aGFyYm9yLmxhYjAzLnZpcnR1YWwuYXV0b21hdGVzdHVmZi5pb4IGaGFyYm9yMA0G
        CSqGSIb3DQEBDQUAA4ICAQDgYqh3GviVFMPFQif27rh4fxnqmEmyjoAwtLEKfLD8
        DJna/bth7QqEdndAdi6XkuPzGbYz1Im/9NoKAuNoCKtxleI24scIl1aGczMntYfR
        LAhpofgtKRY9SjqFIaRVEfxpdGqPao+h0OxLL6knVNfIh0Z0lOhFKBQRGiBXDHnd
        JpYeFNsPx6gLrPXyn97x3mn+yoBIWlb9QKhVnjuST+xQC3mXfL1LgLcliROrI+cY
        Ei1OII9Zn1uwBdnUftvbsz3luWbTIDcimja3ste1+Q4pJ+Mf8ZV3JAQ4+3NZEHwz
        8aDa5fBCNKIrVeFMfJw1+Wv+df8RxWBn1mTstjeFBe/qQTBsfQK+D4AiWu89rlDG
        Jjn7RQfLcat8RUmwsuhSp1HNDj7dAXv3oaWMA4mNN/AlP2WnAZhsugBgbfLg4VpF
        ZIM4BZCYPS+pLhZrM4qgMgS+l8fj3n9f9k7Q16WgGN9n1MNbMtd8bvEcVXrc6Eld
        ZTGZyanEhh/Mv7bCO1UNAo7eX0KT2IAqjmBlCSy6bDVY41LLUgeO33EPGiV1R9Tz
        hN7OUfTvTU+GshC4yJUOAJQUQj/OYJUAioasDN3lQ0FVgWoy/Ni2KEuxkeI8jE02
        HAiMFH5fK9zXlz5rrT+ZFkxBI9Vy0xerzbyuHx1nusb2Qv7iS72QxHLhBkFwJw0f
        lg==
        -----END CERTIFICATE-----
      tls.key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKQIBAAKCAgEAqAkKrd4NVNO2AcVgd212ZvoGgsHiXA2jgx4CdMVS0mJsT1A6
        QClYBf20LHWlHISI8aamF6+CJ6JTmi+Ha8IHCBH2rgS4FceXXoeY6VowEGJ1Nq/s
        FA42ErdFABGHQzWtfbLOOYcQ38ZBgmi/brLHrJL4oWgbBp4Q/RspH3ZTmI7mz8fp
        34PrURjY8lo7MdeXASoHU6WqGZ25cO2Pk1gLvbFKg9daQNvjVcijWRA/w7yJSLEY
        gpiGtf/pfGlZs6R/i8EGEcZY82xOdV//0q4cgzq95QgXbG7jmmbaR0hfKXKXtT6+
        6y0FBCbImVsON8eBWsu57nlSoz64zn1mlbSejBa/AEN6WJhEf31sTkX6dX+Gzzmp
        +Bhz9z/S2vWiyRAtQAAX+PI05CwVOG1yksCo+wMYildEw3Sju49C38il/HAZnkgi
        a1anNsdRMVvpIlcHUY/YivlOOoez4VJctpaDwtgTnHVQdFNPjDSJimTRxmjwK+3Z
        w/lZQdAzC/1woE9HiNLJMbLf9vWzjZGCxwDIET820GxK1ye5NyIBYGHC3P35U7BG
        KNxJXVxRKN9xz9aBcZQ3mwu3lShUOz/OvlD7rLEm65PhoFJEcwUIV4CC8wDyf+js
        TH+E3gFWlh0N5qES2cG9DqVbBImAiNJJZD5SMDTw/sOhDq0/mR6VCJLsbXMCAwEA
        AQKCAgAXiDygoMpJKOUCVnvt/bxpK3ah9TkYHyjZAejiJYg1wmbcrKWbuq6DGEaV
        O1yGI+Fxxh7YjlGx7z+6BhH2+1M0xB9Bu5N0KWF/cYnulBzLDp7Pq89p95uG/3eA
        TPQea3QCeHn9AHdSf1dJRhYZEJx6BJMhN40hXh2O9LDLoSyP3uNgEeUk0jqwPsST
        HCPSFRkmppYkFr09nSMNN5e10MzEIgIHeK9BCgpKRzDpFid35/1p2rNOBsJG1rIC
        JFbVm6HpFn0dHCP04yQRuAIBpTSFBEL3wixVmSnyw5iqBu6cxVmNnl3qXYGoVS4e
        m+vfz+bDqmg9h2wVRIFpGZK2QHc7eQlGKiWUsyDcELrb04CQ2AmfsJ4bREIFRXKx
        VSJSU63p1Cj5eWQWRhUt6WhLoZEBhrjpXYXhm7yalyWbfN+MpOzg66lWUMnRjDAU
        tvi6X5eUxnGecCjy/yn+SRDIK4mD1w9AvD8cNojqRrVn34VrlldrWHej7T+jf8D8
        fpDqY0du5WPay5bcifVRlHmeSLYgiYTVINp2YCYtFf5b08X3FYlw34ObOSr3US98
        hpra76wDkSyXe13BLrfNGpxgJwg50hoS8psWxMT4B/i9dGaj/Bphf7gECbRag9RY
        /GuRc/T1+QnKERyNirhYj8WAkWU3aTTMFkj8Xb8rHvqu0AtrQQKCAQEA15SSnASk
        Rh0N+uEJEvBIXu6qPy4mk6XJXBROQARUogj98dzDaA0JgOtYc7Zp/bRyEcgmKKUC
        0hyHilsWACG7PTvspJ/kDcvKYpAM4XfJsS0Bkcs9tV4DsQ+ODacRHKxCvW++U1AC
        G7kjUOrKwxt+/hw1G5OClfs0Ov/zdnkV/NmEIcCv2fSbaiVLAUUYYes54qztZIPu
        qdLmv8DCC38OU4Gyv+nVo085STuAQR0moc7lDyayDiMZIlNEr1F+RnxNcJ+4KCSR
        lCQLzMBfQ4phfPxoll2N+XvN9WCrFcWdaT3BDc0VXCOaN4m02kL1LMBOMOY8Ipxr
        sdQLC5J9wNkSEQKCAQEAx4pm3UzKOZCfJ2uf10L00qYZM3JIRq4dnXScq0CjdRuu
        Rw3r5HwZiMJWR8Xy0hxyaa/kz8D4GK0SjgVWPOmE2nWL6aAKJ3AVJQ7FVaPLchXF
        B6LWnZpT9JI11wFeZW7dMbRxFgMcbceXCMg8nw3U1yKvsqwb4B22IML1usCe5sTC
        kAsDLH7oKF94AwOk2VCBdilqX/xCvF024pMhX6SD+57j6SajiD4919+qkYRtHC5b
        uuULWwrKVU2sW6zCF/yyz0lOLdDEcLQZ3/N4dRaujxuzoYH54yFvUsjDyi6EQKKO
        haRafsDaTVZMEmjxFGvCQxLst4aLB5gow3cVif6DQwKCAQASS7+tkg9HDAw1sIeO
        nenmdKbqOcZ4XWebcvW5JSTxo4W50xyaZhDaah7VozOXnorXy37BkE+O+XDfYx+Y
        30P+zGknB5LZQORqPQN61ym86a7qaq9QByyVCFbr/bPMFSqM3UDv3ShwpePDaEnR
        CTJb6pTvRDOe+vTR1QsakOg2z1cRbkL+Ym4WMhgNgYmyNb5x6G81SqUksIt41qkh
        RKU4nRdIhlXlSEH6XxxhalHvBZoXERenb38glKSNpILtBHumBUgh0Aiy4+REekcb
        elEPxHQz3ri/5avzGUMr09uqJN2PiEo5yaO69ursYyZfp+p65+9OmKvjKbXOQ558
        kW+hAoIBAQCKQonX2PdeP6knhVkxrIE63EAl94/A+bAng79yoc0gvddaAHlszdhb
        fFyQSsZfc7qLJIdktI6zemia43PHrP6S6FPTw0KF5RGhpcRx/JZhLFhjXB9dAKwf
        kJehrJ8dpV26rQ6Wc/1ky6EJQsVOaCUMFEqtgLen6K5jsPLXPdRcjgVKDXdbg2uV
        XeEoJYQ516B8oWHFtGMBZY08HTpIrROOa5/70vwI0SfExoPHZHy9xBlnPIFLygQ8
        ax98Pg4W1M+I9YAoGrmiZghvtqHGb7rwCf/Dbu4YxPf/4oBXPTgCGSCr1R+nKDWa
        1KrNLs2smqX2F8zRtXXsAzBrj73q6eFFAoIBAQCVhLbBL3ESqmKcHJskkPMxTGIO
        9fhz57hYEDMMOB+7nTkoqTQaHzMm2ubm30DjTO9wN80aWMRne3r4osQ+oX8Fnd7H
        EAqXijiV2Lyz6C5XngSJzUR8+8xoomj6oE3PuwMKEapHigNTiH5eZExj6X0eoe+8
        OckjTDKMXP8C3qJscLROHvnOgZAb2yIducyY4/Tvl5dPU/XtwMyvyX8QB6AgWbGQ
        ILZmmmhGb+1d+ypTjVw6oNzB2nBuCgTqdC3HMGZ1fLaR7grydiBVHIkdGi5RGAdW
        RitBT1i/Pg/OTXN10YO/EmgnDm8ZT9QNRtpw0F9YxN+Fv9H3KF64xjUrjxQ0
        -----END RSA PRIVATE KEY-----
    enableContourHttpProxy: false
    harborAdminPassword: Harbor12345
    secretKey: CFbcoIimPaaxlzIF
    database:
      password: 2NVlqclAwSAkgSQZ
    core:
      replicas: 1
      secret: n46YDKTP3XxkoVpa
      xsrfKey: nbbKMXjH81NcoF8SrFxNhN4KIoVJTjSn
    jobservice:
      replicas: 1
      secret: NADDcpRNL1DxYloT
    registry:
      replicas: 1
      secret: pWY6ytq4UnIqOU7z
    notary:
      enabled: false
    trivy:
      enabled: true
      replicas: 1
      gitHubToken: ""
      skipUpdate: false
    persistence:
      persistentVolumeClaim:
        registry:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 10Gi
        jobservice:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 1Gi
        database:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 1Gi
        redis:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 1Gi
        trivy:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 5Gi
      imageChartStorage:
        disableredirect: false
        type: filesystem
        filesystem:
          rootdirectory: /storage
        azure:
          accountname: accountname
          accountkey: base64encodedaccountkey
          container: containername
          realm: core.windows.net
        gcs:
          bucket: bucketname
          encodedkey: base64-encoded-json-key-file
          rootdirectory: null
          chunksize: 5242880
        s3:
          region: us-west-1
          bucket: bucketname
          accesskey: null
          secretkey: null
          regionendpoint: null
          encrypt: false
          keyid: null
          secure: true
          v4auth: true
          chunksize: null
          rootdirectory: null
          storageclass: STANDARD
        swift:
          authurl: https://storage.myprovider.com/v3/auth
          username: username
          password: password
          container: containername
          region: null
          tenant: null
          tenantid: null
          domain: null
          domainid: null
          trustid: null
          insecureskipverify: null
          chunksize: null
          prefix: null
          secretkey: null
          accesskey: null
          authversion: null
          endpointtype: null
          tempurlcontainerkey: null
          tempurlmethods: null
        oss:
          accesskeyid: accesskeyid
          accesskeysecret: accesskeysecret
          region: regionname
          bucket: bucketname
          endpoint: null
          internal: null
          encrypt: null
          secure: null
          chunksize: null
          rootdirectory: null
    proxy:
      httpProxy:
      httpsProxy:
      noProxy: 127.0.0.1,localhost,.local,.internal
    pspNames: null
    metrics:
      enabled: false
      core:
        path: /metrics
        port: 8001
      registry:
        path: /metrics
        port: 8001
      exporter:
        path: /metrics
        port: 8001
